# docker-compose.yml
version: '3.8'

services:
  pocketbase:
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
      args:
        VERSION: 0.22.27
    ports:
      - "8090:8090"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "4173:4173"
    environment:
      - PUBLIC_POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped