version: "3.7"
services:
  pocketbase:
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
    container_name: pocketbase
    restart: unless-stopped
    environment:
      ENCRYPTION: ${ENCRYPTION}
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_migrations:/pb_migrations # Add migrations volume
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
