version: "3.7"
services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      pocketbase:
        condition: service_healthy
    environment:
      PUBLIC_POCKETBASE_URL: ${PUBLIC_POCKETBASE_URL}
      PUBLIC_APPLICATION_NAME: ${PUBLIC_APPLICATION_NAME}
      PUBLIC_APPLICATION_URL: ${PUBLIC_APPLICATION_URL}
      HOST: "0.0.0.0"
    networks:
      - app-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5173 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv
      - ENCRYPTION
    environment:
      ENCRYPTION: ${ENCRYPTION}
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge