version: "3.7"
services:
  pocketbase:
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
    container_name: pocketbase
    restart: unless-stopped
    environment:
      ENCRYPTION: ${ENCRYPTION}
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pocketbase-network

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: blink-app
    ports:
      - "4173:4173"
    environment:
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
      - PUBLIC_APPLICATION_NAME=${PUBLIC_APPLICATION_NAME}
      - PUBLIC_APPLICATION_URL=${PUBLIC_APPLICATION_URL}
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - pocketbase-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4173 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

# Define networks at the bottom of the file
networks:
  pocketbase-network:
    name: pocketbase-network
    driver: bridge