version: "3.8"

services:
  web-dev:
    container_name: blink-web-dev
    build:
      context: .
      dockerfile: Dockerfile.sveltekit
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      # Add Bun cache volume for faster builds
      - bun-cache:/root/.bun
    environment:
      - NODE_ENV=development
      - PUBLIC_APPLICATION_NAME=your-app-name.com
      - ORIGIN=http://localhost:5173
      - POCKETBASE_URL=http://pocketbase:8090
    networks:
      - blink-network
    depends_on:
      pocketbase:
        condition: service_healthy

  pocketbase:
    container_name: blink-pocketbase
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    networks:
      - blink-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  blink-network:
    driver: bridge

volumes:
  pocketbase_data:
    driver: local
  bun-cache:
    driver: local
