version: "3.7"
services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      - pocketbase
    environment:
      PUBLIC_POCKETBASE_URL: ${PUBLIC_POCKETBASE_URL}
      PUBLIC_APPLICATION_NAME: ${PUBLIC_APPLICATION_NAME}
      PUBLIC_APPLICATION_URL: ${PUBLIC_APPLICATION_URL}
    networks:
      - app-network

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - serve
      - --http=0.0.0.0:8090
    environment:
      ENCRYPTION: ${ENCRYPTION}
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge